/*
 * This source file was generated by the Gradle 'init' task
 */
package bd2;

import java.util.List;
import bd2.model.*;
import bd2.model.Venta;

public class App {
    public static void main(String[] args) {
        System.out.println("Generando datos de prueba...");
        List<Venta> ventas = bd2.Util.GeneradorDatos.generarVentasDePrueba();
        System.out.println("¡Se generaron " + ventas.size() + " ventas con éxito!");
        
        // Llamar al mapper para guardar el archivo y listo
        bd2.Mappers.VentasMapper.guardarVentasEnArchivoJson(ventas, "ventas.json");
    }
        
}
